Update update-json.yml

diff --git a/.github/workflows/update-json.yml b/.github/workflows/update-json.yml
--- a/.github/workflows/update-json.yml
+++ b/.github/workflows/update-json.yml
@@ -17,7 +17,9 @@ jobs:
 
       - name: Fetch updated JSON from Google Drive
         run: |
-          curl -L "https://drive.google.com/uc?export=download&id=1fru8p2v4eEr_Bu7Tsr2_f_objKC7lTWZ" --output data/drawings_data.json
+          FILE_ID="1fru8p2v4eEr_Bu7Tsr2_f_objKC7lTWZ"
+          FILENAME="data/drawings_data.json"
+          wget --no-check-certificate "https://docs.google.com/uc?export=download&id=$1fru8p2v4eEr_Bu7Tsr2_f_objKC7lTWZ" -O $FILENAME
 
       - name: Verify JSON file exists
         run: |
@@ -26,6 +28,15 @@ jobs:
             exit 1
           fi
           echo "✅ JSON file successfully downloaded."
+
+      - name: Verify JSON file format
+        run: |
+          if jq empty data/drawings_data.json; then
+            echo "✅ JSON file is valid."
+          else
+            echo "❌ Error: JSON file is not valid!"
+            exit 1
+          fi
 
       - name: Commit and push if changed
         run: |
